[package]
name = "maharit-viz"
description = "Visualization for MaharitDB graphs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
maharit-core.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
