[package]
name = "maharit-storage"
description = "Storage engine for MaharitDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
maharit-core.workspace = true
thiserror.workspace = true
flate2.workspace = true
zstd.workspace = true
tokio.workspace = true
serde.workspace = true
bincode.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures-util.workspace = true
maharit-core.workspace = true
