[package]
name = "maharit-server"
description = "CLI and server for MaharitDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "maharit"
path = "src/main.rs"

[dependencies]
maharit-core.workspace = true
maharit-storage.workspace = true
maharit-query.workspace = true
rustyline.workspace = true
colored.workspace = true
tokio.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pemfile.workspace = true
webpki-roots.workspace = true
toml.workspace = true
