[package]
name = "maharit-core"
description = "Core graph data structures for MaharitDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["japanese"]
japanese = ["dep:lindera"]

[dependencies]
dashmap.workspace = true
thiserror.workspace = true
lindera = { version = "2.2", features = ["embed-ipadic"], optional = true }
rayon = "1.10"
serde.workspace = true
